name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Install Backend Dependencies
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Backend Requirements
        run: |
          if [ -f backend/requirements.txt ]; then
            cd backend
            pip install -r requirements.txt
          else
            echo "No backend/requirements.txt found. Skipping."
          fi

  frontend:
    name: Install Frontend Dependencies
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Frontend Packages
        run: |
          if [ -f frontend/package.json ]; then
            cd frontend
            npm install
          else
            echo "No frontend/package.json found. Skipping."
          fi
